name: auto_gen_struct
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  args: 2.3.1

dev_dependencies:
  flutter_lints: ^1.0.0

executables:
  auto_gen_struct:
